### ISSUE TITLE
why you use StreamProvider in providerV3 sample code

### ISSUE THREAD

**Issue by MahdiPishguy** [FilledStacks/flutter-tutorials#22]
could you describe me why you use `StreamProvider` for `User`
?
```dart
List<SingleChildCloneableWidget> uiConsumableProviders = [
  StreamProvider<User>(
    builder: (context) => Provider.of<AuthenticationService>(context, listen: false).user,
  )
];
```

**Comment by FilledStacks** [comment]
Because User is a Stream. That's how you provide a Stream through Provider

**Comment by MahdiPishguy** [comment]
your mean is User should be accessible in all of application part? for example update user data. get data from user and `User` can be changeable every time?

**Comment by FilledStacks** [comment]
No, that's the reason " why you use StreamProvider for User" . I'm using a StreamProvider because user is a stream. You can access it anytime to get the information. If you want to manipulate the user I'd create a userService with the functionality and move that stream out of the AuthenticationService into the UserService.

**Comment by MahdiPishguy** [comment]
is this correct?

```dart
class UserService {
  StreamController<User> _userController = StreamController<User>();

  Stream<User> get user => _userController.stream;

  Future updateUser() async {
  }
  
  Future deleteUser() async {
  }
}
```

thanks in advance

**Comment by FilledStacks** [comment]
Yes, that's how I would handle it. Instead of merging the user related functionality in with the AuthenticationService keep the responsibility single and make a separate service that will handle modifying and updating the user.

Add a void dispose call and close the controller. The new version of getit allows you to dispose services as well although for a singleton service that's alive an entire lifetime that doens't help much.

**Comment by MahdiPishguy** [comment]
@FilledStacks if i make a simple sample of this architecture can you check that how can we use this feature as separated class?

**Comment by FilledStacks** [comment]
Unfortunately not, I’m only helping out now in between some sets of work I’m doing. I won’t be able to do code reviews since there are clients paying me to do that. You can email me at dane@filledstacks.com<mailto:dane@filledstacks.com> if you want to setup a code review session.

Regards,
Dane Mackier

________________________________
