### ISSUE TITLE
Provider pattern with exception handling

### ISSUE THREAD

**Issue by PandaGeek1024** [FilledStacks/flutter-tutorials#32]
Hi, first of all, these are really great tutorials. I really love what you have done here.

After viewing most of them I have build my app with provider approach from this article:
https://www.filledstacks.com/post/flutter-architecture-my-provider-implementation-guide/

The way of handling idle and busy is awesome but it looks like it is missing the exception-handling part, sure I can write my own way of exception handling. But Im just wondering if there is an existing sample that has already got a nice approach integrated with your current design? Thanks

**Comment by FilledStacks** [comment]
Hi Jay,

Thanks for kind words. I haven’t covered exception handling in a tutorial specifically. It’s not something I have a general strategy for, each service handle their exceptions differently. Because I have access to my DialogService at a service level I would usually use that for general errors. The rest of the exceptions is handled at the ViewModel level. This allows me to match the error feedback with the intended designs per view.

________________________________
