### ISSUE TITLE
flutter-tutorials/042-firebase-cloud-storage/lib/models/post.dart

### ISSUE THREAD

**Issue by klops-za** [FilledStacks/flutter-tutorials#58]
Awesome tutorial tx

Would it be possible to add a example of how to populate a field of type array
i.e. Time [ int hours, int min, int sec ]

**Comment by FilledStacks** [comment]
Thank you. 

```
var time = [10, 43, 23]
```

Should do the trick right?

**Comment by AlraziBashir** [comment]
Hey Dane,

Thanks for helping me learn Flutter! I am working on your responsive flutter we app tutorial #33 and I am unable to pass the ScreenTypeLayout Widget that you used in the Navigation_Bar.dart file. I hav followed your steps and added the responsive_builder package. Your help is appreciated thanks.
![Screen Shot 2020-04-21 at 1 43 15 PM](https://user-images.githubusercontent.com/53784936/79896198-0ea29f00-83d6-11ea-9d8c-bb50af1a6953.png)
![Screen Shot 2020-04-21 at 1 44 48 PM](https://user-images.githubusercontent.com/53784936/79896364-46114b80-83d6-11ea-9f34-4048031051ed.png)

**Comment by AlraziBashir** [comment]
![Screen Shot 2020-04-21 at 1 45 41 PM](https://user-images.githubusercontent.com/53784936/79896458-67723780-83d6-11ea-820e-13e8f6296828.png)

**Comment by Raptor121-SA** [comment]
@AlraziBashir You have to import the responsive_builder package at the top of NavBar.dart file.

**Comment by FilledStacks** [comment]
@AlraziBashir there's some other stuff you'll have to learn before learning flutter to give you a better understanding of programming. What you're experiencing is what's called scope in a programming language. You should read up on how scope it handled in the common typed programming language. A field can't be seen outside of its class because of scope, a variable created in a function can't be seen in another function, because of scope and in your case. A class can't be seen outside of its file, unless it's imported. 

Flutter will probably be very difficult for you in the sense that a problem that's not an actual problem will be difficult for you. Like a missing import. where most of us will press ctrl+. and select import. You don't even know it's a scoping issue. Which means when you follow other tutorials that don't show all the imports you'll run into more problems that doesn't require code to be solved. 

I suggest you get a good grip on object oriented programming, just the basics, then continue with Flutter after. Unless you did that in the month since posting this. Then it should be all good :D
